SET timezone TO "+00:00";     

CREATE TABLE IF NOT EXISTS bike_agg_minneapolis (                                         
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,                                             
  bikes integer NOT NULL,                                                                             
  spaces integer NOT NULL,                                                                            
  unbalanced integer NOT NULL                                                                         
);

CREATE TABLE IF NOT EXISTS bike_ind_minneapolis (
  tfl_id integer NOT NULL,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tfl_id,timestamp),
  KEY timestamp
);

CREATE TABLE IF NOT EXISTS bike_agg_boston (                                         
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,                                             
  bikes integer NOT NULL,                                                                             
  spaces integer NOT NULL,                                                                            
  unbalanced integer NOT NULL                                                                         
);

CREATE TABLE IF NOT EXISTS bike_ind_boston (
  tfl_id integer NOT NULL,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tfl_id,timestamp),
  KEY timestamp
);

CREATE TABLE IF NOT EXISTS bike_ind_newyork (
  tfl_id integer NOT NULL,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  total_docks integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tfl_id,timestamp)
);

CREATE TABLE IF NOT EXISTS bike_agg_newyork (
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  unbalanced integer NOT NULL,
  total_docks integer NOT NULL,
  PRIMARY KEY (timestamp)
);

CREATE TABLE IF NOT EXISTS bike_ind_chicago (
  tfl_id integer NOT NULL,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  total_docks integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tfl_id,timestamp)
);

CREATE TABLE IF NOT EXISTS bike_agg_chicago (
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  unbalanced integer NOT NULL,
  total_docks integer NOT NULL,
  PRIMARY KEY (timestamp)
);

CREATE TABLE IF NOT EXISTS bike_agg_washingtondc (                                         
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,                                             
  bikes integer NOT NULL,                                                                             
  spaces integer NOT NULL,                                                                            
  unbalanced integer NOT NULL                                                                         
);

CREATE TABLE IF NOT EXISTS bike_ind_washingtondc (
  tfl_id integer NOT NULL,
  bikes integer NOT NULL,
  spaces integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tfl_id,timestamp),
  KEY timestamp
);

#Clears out postgres autogenerated Key column
ALTER TABLE bike_ind_minneapolis DROP COLUMN key;
ALTER TABLE bike_ind_washingtondc DROP COLUMN key;
ALTER TABLE bike_ind_boston DROP COLUMN key;
ALTER TABLE bike_ind_newyork DROP COLUMN key;
ALTER TABLE bike_ind_chicago DROP COLUMN key;


\copy bike_agg_minneapolis FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/bike_agg_minneapolis_c.csv' DELIMITER ',' CSV; 
\copy bike_ind_minneapolis FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/bike_ind_minneapolis_c.csv' DELIMITER ',' CSV;

\copy bike_ind_boston FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_ind_boston_c.csv' DELIMITER ',' CSV;  
\copy bike_agg_boston FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_agg_boston_c.csv' DELIMITER ',' CSV;  

\copy bike_agg_washingtondc FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_agg_washingtondc_c.csv' DELIMITER ',' CSV; 
\copy bike_ind_washingtondc FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_ind_washingtondc_c.csv' DELIMITER ',' CSV; 


\copy bike_agg_newyork FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_agg_newyork_c.csv' DELIMITER ',' CSV; 
\copy bike_ind_newyork FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_ind_newyork_c.csv' DELIMITER ',' CSV; 

\copy bike_agg_chicago FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_agg_chicago_c.csv' DELIMITER ',' CSV; 
\copy bike_ind_chicago FROM '/mnt/data1/BikeShare/raw_data/casa.oobrien.com/misc/bikedata/test/bike_ind_chicago_c.csv' DELIMITER ',' CSV; 

